### ISSUE TITLE
Index debe mostrar las rutas de las API's

### ISSUE THREAD

**Issue by Gidrek** [civica-digital/api-estados#12]
En el index se deben mostrar las rutas de las API's y documentación en su defecto.

**Comment by juanjcsr** [comment]
¿Tienen roadmap de cómo implementar la documentación? ¿Usar algún framework? Por ejemplo, con [Swagger](http://swagger.io)?

**Comment by mikesaurio** [comment]
Yo preferiria que fuera con Swagger, utilice esta dependencia pero tuve errores @juanjcsr https://github.com/xerions/phoenix_swagger, tienes alguna sugerencia?

**Comment by juanjcsr** [comment]
Estuve haciendo pruebas con esa misma biblioteca hace rato pero la documentación no está actualizada y salen muchos errores. Si encuentro algo, les digo, @mikesaurio

**Comment by mikesaurio** [comment]
Terminado y se encuentra en /swagger/#
