### ISSUE TITLE
Dockerizar repo para fácil uso

### ISSUE THREAD

**Issue by rafaelcr** [civica-digital/api-estados#4]

**Comment by juanjcsr** [comment]
Puedo trabajar en ésta mejora, tengo una configuración de Docker para modo desarrollo que he utilizado en algunos proyectos y funciona bien.

Ojo que solo funciona para modo desarrollo. Para producción puedo hacer otra después de terminar este issue :)

**Comment by Gidrek** [comment]
Aún no estoy muy seguro de implementar docker para producción ya que una de las ventajas de la BEAM es que puede utlizar todos los procesadores sin necesidad de configuración y al crear el contenedor nosotros tendríamos que manejar manualmente eso, del esto último no estoy tan seguro.

**Comment by juanjcsr** [comment]
Estoy de acuerdo. En producción he usado tanto exrm como Distillery y funciona bien. Lo de Docker para producción lo comentaba porque se de varios Repos que lo usan, sin embargo soy de la misma idea, sin Docker :)

**Comment by Gidrek** [comment]
Se utiliza docker para dev
